### ISSUE TITLE
Refine Data Models: expected impact on the prototype

### ISSUE THREAD

**Issue by cmrlourenco** [SKA-ScienceDataProcessor/FastImaging#11]
Hi Tim,

I've noticed the recent activity on the topic [Refine Data Models for PIP.IMG](https://confluence.ska-sdp.org/display/IMG/Refine+Data+Models+for+PIP.IMG) in which you participate actively. After skimming through the page it becomes clear that any outcomes of the debate will impact the prototype.
In your expert opinion, how likely is the refined version to become a lot different to the current reference implementation? Will it be a complete overhaul, or just an adjustment of the data models keeping the flow and interfaces?

Should the expected impact be large, I'll need to take action as soon as possible in order to prepare the project for a smooth adjustment later on when changes start to appear.

**Comment by timstaley** [comment]
Hi Cesar, 
this is probably best discussed via Skype - let's arrange something via email.

(In short - I don't think this is something we need to worry about just yet - let's focus on getting the algorithms correctly implemented, tested, and benchmarked. But I'll explain more in discussion.)
