### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by MonroeD** [SKA-ScienceDataProcessor/FastImaging#20]
FastImaging-master/src/stp/imager/imager.h:112:87: error: cannot convert ‘std::complex<double>*’ to ‘double*’ for argument 3’ to ‘void cblas_zdscal(blasint, double, double*, blasint)’

and other same errors in imager.h

**Comment by timstaley** [comment]
Hi there,
can you give us some information about your build environment - Linux version, compiler version, etc?

We are only targeting Ubuntu 16.04  / Debian-testing environments, currently. You may have more success building under a virtual machine with one of those. To that end, you can load up a virtual machine using 'Vagrant' by following the instructions here:
https://github.com/SKA-ScienceDataProcessor/FastImaging/tree/master/vagrant

**Comment by lfrlucas** [comment]
This issue shall not be present in the latest version. I'll close the issue. Thanks for reporting.
