### ISSUE TITLE
Convolution functions

### ISSUE THREAD

**Issue by timstaley** [SKA-ScienceDataProcessor/FastImaging#3]
Implement basic radial / 1d functions `r -> f(r)`, for:
- Tophat (aka 'pillbox'): `f(r) = 1 if r< r_thresh, otherwise  f(r)=0`. (This is terrible in real imaging practice but makes a convenient test-function for verifying convolutions procedures, etc)
- Sinc function: `f(r) = sin(r)/(w*r)` where `w` is a width parameter (usually 1.0). 
- Gaussian sinc: `f(r) = sin(pi/alpha_1*(r+eps))/(pi*(r+eps)) * exp(-(r/alpha_2)**2)`,  where
  alpha_1 = 1.55, alpha_2 = 2.52, and eps = 1e-10 to avoid div by  zero.

(For reference see e.g. Chapter 7 of Taylor 1998, **Synthesis imaging in radio astronomy II**).

(Prolate spheroidal to be tackled later).

NB all functions are truncated by the finite pixel-width of the convolution area.

Note that we will want to use these functions interchangably as 'drop-ins' for the convolution routine. For an initial implementation they can simply be functions, so they must all have the same function call signature. Any variable parameters (e.g. r_thresh for the tophat) can be hard-coded. In the long run we might consider switching to more sophisticated implementation that allows for initialization with varying parameters (a callable class).

Python implementation (work-in-progress) can be found [here](https://github.com/SKA-ScienceDataProcessor/FastImaging-Python/blob/master/src/fastimgproto/gridder/conv_funcs.py), with [unit-tests here](https://github.com/SKA-ScienceDataProcessor/FastImaging-Python/blob/master/tests/test_gridder/test_conv_funcs.py).

**Comment by goncaloalmeida** [comment]
Regard this topic.
In Sinc convolution implementation, we verified that the tolerance used for the test pass was to be higher (0.091) that the used in other convolution functions (0.002).
It's normal this convolution reach the same value with different tolerance?

**Comment by timstaley** [comment]
Done:
https://github.com/SKA-ScienceDataProcessor/FastImaging/blob/e0f8de8a3f3e2879a1d4d5d50e509ab630e454e7/src/libstp/convolution/conv_func.cpp
