### ISSUE TITLE
Stylistic issue: care with ``using namespace``

### ISSUE THREAD

**Issue by timstaley** [SKA-ScienceDataProcessor/FastImaging#8]
This is a low-priority, but I wanted to bring up use of the `using namespace` operator, as here:
https://github.com/SKA-ScienceDataProcessor/FastImaging/blob/2bf7f0bad95d8aa4d3cc3db223de2c4824b5ffc6/src/libstp/convolution/conv_func.h#L15

At the risk of very long function definitions, I would suggest we restrict use of the `using namespace` aliases to implementation (.cpp) files, and always use fully qualified names in the header files. The reasoning behind this is that otherwise you are effectively throwing the namespace away and injecting the full contents of the 'arma', 'std' namespaces in the global namespace of any client code which calls the stp library, which potentially causes confusion and /or name collisions (e.g. what if I'm using another library with a `mat` class, or, where do I go to look up the documention on the `accu` function?

**Comment by cmrlourenco** [comment]
I completely agree. In fact, if some FQN is too lengthy we can just make an alias for it ir order to make it less annoying to type.
