### ISSUE TITLE
Simple imaging script (gridding + FFT)

### ISSUE THREAD

**Issue by timstaley** [SKA-ScienceDataProcessor/FastImaging#9]
I've just added a simple imaging script to the Python repository, here: 
https://github.com/SKA-ScienceDataProcessor/FastImaging-Python/blob/master/src/fastimgproto/scripts/simple_imager.py

This gives a simple end-to-end example of loading in visibility data, gridding, applying FT to image space and then writing to file - we should try to mirror this with a C++ implementation to check we get consistent results.

(The FFT calls are here: https://github.com/SKA-ScienceDataProcessor/FastImaging-Python/blob/master/src/fastimgproto/imager.py)

**Comment by timstaley** [comment]
I've just added sample input data (Numpy 'npz' format), which you can find here:
https://github.com/SKA-ScienceDataProcessor/FastImaging-Python/tree/master/src/fastimgproto/resources/testdata

The simple_imager Python script is also now unit-tested, here:
https://github.com/SKA-ScienceDataProcessor/FastImaging-Python/blob/master/tests/test_scripts/test_simple_imager.py

**Comment by goncaloalmeida** [comment]
Can you upload the config.json file used?

**Comment by timstaley** [comment]
Superseded by #15
